export const ADD_ERROR = 'ADD_ERROR';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const ADD_SUCCESS = 'ADD_SUCCESS';
export const REMOVE_SUCCESS = 'REMOVE_SUCCESS';
export const ADD_WARNING = 'ADD_WARNING';
export const REMOVE_WARNING = 'REMOVE_WARNING';
export const ADD_INFO = 'ADD_INFO';
export const REMOVE_INFO = 'REMOVE_INFO';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';

export const CREATE_USER = 'CREATE_USER';

export const VIEW_CARS_ONSITE = 'VIEW_CARS_ONSITE';
export const VIEW_CARS_LOG = 'VIEW_CARS_LOG';
export const VIEW_REGISTERED_CARS = 'VIEW_REGISTERED_CARS';

export const SET_CAR_PROFILE = 'SET_CAR_PROFILE';
export const REMOVE_CAR_PROFILE ='REMOVE_CAR_PROFILE'

export const VIEW_VISITORS_ONSITE = 'VIEW_VISITORS_ONSITE';
export const GET_CLOSED_VISITS_LOG = 'GET_CLOSED_VISITS_LOG';
export const SEARCH_FOR_USERS = 'SEARCH_FOR_USERS';
export const SET_USER_VIA_APPOINTMENT_CODE = 'SET_USER_VIA_APPOINTMENT_CODE'; 

export const SET_USER_LOG = 'SET_USER_LOG';
export const REMOVE_USER_LOG = 'REMOVE_USER_LOG'
export const SET_LOG_PROFILE = 'SET_LOG_PROFILE';
export const REMOVE_LOG_PROFILE = 'REMOVE_LOG_PROFILE'; 

export const VIEW_APPOINTMENTS = 'VIEW_APPOINTMENTS';
export const VIEW_APPOINTMENT = 'VIEW_APPOINTMENT';
export const VIEW_VISITS = 'VIEW_VISITS'; 
export const SET_APPOINTMENT_PROFILE = 'SET_APPOINTMENT_PROFILE';
export const REMOVE_APPOINTMENT_PROFILE = 'REMOVE_APPOINTMENT_PROFILE';